--- #YAML:1.0
name:                Apache2-PodBrowser
version:             0.07
abstract:            show your POD in a browser
license:             ~
author:              
    - Torsten Foertsch <torsten.foertsch@gmx.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache2::Const:                0
    Apache::TestMM:                0
    File::Spec:                    0
    MMapDB:                        0.11
    ModPerl::MM:                   0
    Pod::Find:                     1.3
    Pod::Simple::HTML:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
